### ISSUE TITLE
click >=8 possibly not compatible

### ISSUE THREAD

**Issue by jsphweid** [cceyda/torchserve-dashboard#4]
Couldn't run the dashboard initially

```
Traceback (most recent call last):
  File "/Users/me/Desktop/pytorch-mnist/venv/bin/torchserve-dashboard", line 8, in <module>
    sys.exit(main())
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/torchserve_dashboard/cli.py", line 16, in main
    ctx.forward(streamlit.cli.main_run, target=filename, args=args, *kwargs)
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/click/core.py", line 784, in forward
    return __self.invoke(__cmd, *args, **kwargs)
  File "/Users/me/Desktop/pytorch-mnist/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
TypeError: main_run() got multiple values for argument 'target'
```

After a bit of googling, I found this: https://github.com/rytilahti/python-eq3bt/issues/30

The default install brought in `click==8.0.1`. I had to downgrade to 7.1.2 to get past the error.

**Comment by cceyda** [comment]
Thank you for reporting on this 👍
I have pinned click<8.0,>=7.0  version and did a new release v0.3.3.
I really should learn more about python packaging / dependency management 😅 
I will do another release for torchserve 0.4 tomorrow after I test it out a bit more. If you want to wait.
